/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: e-toma (https://sketchfab.com/e-toma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sketchbot-37c871cbd9174f67bda4c10d19a97ed0
Title: Sketchbot
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from "../assets/3d/contactBot.glb";

export function ContactBot({ currentAnimation, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);

  // useEffect(() => {
  //   Object.values(actions).forEach((action) => action.stop());

  //   if (actions[currentAnimation]) {
  //     if (currentAnimation === "Computation") {
  //       actions[currentAnimation].startAt(-100);
  //     }

  //     actions[currentAnimation].play();
  //     console.log(currentAnimation)
  //   }
  // }, [actions, currentAnimation]);

  // Change animation when the index changes
  useEffect(() => {
    // Reset and fade in animation after an index has been changed
    actions[currentAnimation].reset().fadeIn(0.5).play();
    // In the clean-up phase, fade it out
    return () => actions[currentAnimation].fadeOut(0.5);
  }, [actions, currentAnimation]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="contactBotglb">
          <group
            name="Sketchfab_model"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.023}
          >
            <group
              name="ca242c97b9dd43a6bdc52916c4a7aa5bfbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="Object_2">
                <group name="RootNode">
                  <group name="BOT" position={[-1.665, -0.905, 1.227]}>
                    <group name="Object_5">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_8"
                        geometry={nodes.Object_8.geometry}
                        material={materials.Nuovo}
                        skeleton={nodes.Object_8.skeleton}
                        morphTargetDictionary={
                          nodes.Object_8.morphTargetDictionary
                        }
                        morphTargetInfluences={
                          nodes.Object_8.morphTargetInfluences
                        }
                      />
                      <skinnedMesh
                        name="Object_10"
                        geometry={nodes.Object_10.geometry}
                        material={materials.Merged_A7_export}
                        skeleton={nodes.Object_10.skeleton}
                        material-depthWrite={true}
                      />
                      <group
                        name="Object_7"
                        position={[-4.995, -3.942, 3.68]}
                      />
                      <group
                        name="Object_9"
                        position={[-1.665, -0.905, 1.227]}
                      />
                      <group name="EYE" position={[-3.33, -3.037, 2.453]} />
                      <group name="Merged_A7_export" />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
